import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/(dashboard)/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        "secondary-fixed": "#99f89e",
        "surface-container-high": "#e7e8e9",
        "on-secondary": "#ffffff",
        "surface-container": "#edeeef",
        "on-background": "#191c1d",
        "on-primary-fixed-variant": "#1c4197",
        "inverse-surface": "#2e3132",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#0e742c",
        "on-tertiary-container": "#ff7675",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        background: "#f8f9fa",
        "surface-tint": "#3959b0",
        "surface-dim": "#d9dadb",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "tertiary-container": "#760013",
        "on-tertiary-fixed-variant": "#93001a",
        "on-surface-variant": "#444652",
        "on-secondary-fixed": "#002106",
        error: "#ba1a1a",
        "primary-container": "#003087",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb3b0",
        "outline-variant": "#c4c6d4",
        "on-primary-container": "#7f9df8",
        "secondary-fixed-dim": "#7edb85",
        secondary: {
          DEFAULT: "#006e26",
          foreground: "#ffffff",
        },
        "surface-container-highest": "#e1e3e4",
        primary: {
          DEFAULT: "#001d59",
          foreground: "#ffffff",
        },
        "on-tertiary-fixed": "#410006",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#b4c5ff",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed-variant": "#00531b",
        "on-primary-fixed": "#00174b",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        outline: "#747683",
        "on-surface": "#191c1d",
        "primary-fixed": "#dbe1ff",
        "secondary-container": "#99f89e",
        tertiary: "#4d0009",
        surface: "#f8f9fa",
        "tertiary-fixed": "#ffdad8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        "container-margin": "20px",
        gutter: "16px",
        "tap-target-min": "48px",
        "card-padding": "24px",
      },
      fontFamily: {
        sans: [
          "var(--font-jakarta)",
          "Inter",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        inter: [
          "var(--font-jakarta)",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
        "label-sm": ["var(--font-jakarta)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-jakarta)", "Inter", "sans-serif"],
        "question-text": ["var(--font-jakarta)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-jakarta)", "Inter", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    require("tailwindcss-animate"),
  ],
};

export default config;
